## Introduction to TensorFlow

#### What is TensorFlow?
<li>TensorFlow is an end-to-end platform for machine learning.</li>
<li>Write fast Deep Learning code in Python/other accessible languages (able to run on a GPU/TPU). TPU is Tensor Processing Unit.</li>
<li>Able to access many pre-built deep learning models (TensorFlow Hub).</li>
<li>Whole Stack: preprocess data, model data, deploy model in your application.</li>
<li>Originally designed and use in-house by Google (it is now open-source).</li>

#### Why tensorFlow?
<li>Easy model building.</li>
<li>Robust ML production anywhere.</li>
<li>Powerfull experimentation for research.</li>

#### What is Tensor?
<li>Generally, tensors are some numerical way to represent information or some sort of data.</li>
Watch the video below from YouTube to underestand the Tensors:
<a>https://www.youtube.com/watch?v=f5liqUk0ZTw</a>
<li>Scientificly, tensors are arrays with more than two axes.</li>

<p>In this very first notebook, we are going to use some fundamental concepts of tensors using TensorFlow.

<ol>
    <li>Introduction to Tensors</li>
    <li>Getting information from Tensors</li>
    <li>Manipulating Tensors</li>
    <li>Tensors and Numpy</li>
    <li>Using @tf.function (a way to speed up the regular Python functions)</li>
    <li>Using GPUs with TensorFlow (or TPU)</li>
    <li>Exercises to try for yourself.</li>
</ol>



In [1]:
#Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [5]:
# Creating Tensors with tf.constant()
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [7]:
# Check the number of dimention of a tensor (ndim stands for the number of dimentions)
scalar.ndim

0

In [10]:
# Create a vector
vector = tf.constant([8, 7, 10])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 8,  7, 10], dtype=int32)>

In [11]:
vector.ndim

1

In [12]:
#Create a matrix (a matrix have more than one dimention)
matrix = tf.constant([[9, 11],
                      [3, 6]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 11],
       [ 3,  6]], dtype=int32)>

In [13]:
matrix.ndim

2

In [17]:
matrix2 = tf.constant([[1, 2, 3, 4],
             [5, 6, 7, 8]])
matrix2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [18]:
matrix2.ndim

2

In [23]:
matrix3 = tf.constant([[11., 8.],
                       [4., 6.,],
                       [2., 5.]], dtype = tf.float16) #Specify the data type with dtype parameter
matrix3

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[11.,  8.],
       [ 4.,  6.],
       [ 2.,  5.]], dtype=float16)>

In [24]:
matrix3.ndim

2

In [30]:
# Let's create a tensor
tensor = tf.constant([[[3, 2, 7],
                      [4, 8, 9]],
                      [[10, 7, 4],
                      [11, 2, 3]],
                      [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 3,  2,  7],
        [ 4,  8,  9]],

       [[10,  7,  4],
        [11,  2,  3]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [31]:
tensor.ndim

3

####So far:

<li>Scalar: a single number or Rank 0 Tensor</li>
<li>Vector: a number with direction (e.g. wind speed and direction) or Rank 1 Tensor</li>
<li>Matrix: a 2-dimensional array of numbers</li>
<li>Tensor: an n-dimensional array of numbers or Rank n Tensor (e.g. RGB images in Convolutional Neural Networks.) --> n can be any number.</li>

### Creating tensors with tf.Variable()

In [41]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([12, 8])
unchangeable_tensor = tf.constant([12, 8])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12,  8], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([12,  8], dtype=int32)>)

In [42]:
# Let's try change one of the elements in the changeabe tensor
changeable_tensor[0] = 7

TypeError: ignored

In [43]:
# How about we try .assign()
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 8], dtype=int32)>

In [44]:
# Let's try the unchangeable tensor
unchangeable_tensor[0] = 17
unchangeable_tensor

TypeError: ignored

In [46]:
unchangeable_tensor[0].assign(17)
unchangeable_tensor

AttributeError: ignored

**Ponit**: Rarely in prqactice will you need to decide wether to use tf.constant or tf.Variable to create tensors, as TensorFlow does this for you. However, if in doubt, use tf.constant and change it later if needed.

### Creating Random Tensors
<p>Random Tensors are tensors of some arbitrary size which contain random numbers. </p>
<p>In order to train our Neural Network we need to Initialize with Random weights (only at the begining).

In [82]:
# Create random Tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape = (3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))

# Are they equal? Yes, because we set a seed here.
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor
In other words, sometimes we interested in shuffling the dataset that we have

In [84]:
# Shuffle a tensor (valuabe when you want to shuffle your data so the inherent order does not effect learning process)
not_shuffled = tf.constant([[10, 7],
                            [4, 9],
                            [3, 10]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  9],
       [ 3, 10]], dtype=int32)>

In [85]:
not_shuffled.ndim

2

In [88]:
# Shuffle our non_shuffled_tensor
# Use Shift + Command + Space to check the documentation or help in Google Colab or just use Shift + Tab command in Jupyter Notebook
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3, 10],
       [10,  7],
       [ 4,  9]], dtype=int32)>

In [90]:
# Run the cell again (we will get different order everytime that we run it.)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3, 10],
       [10,  7],
       [ 4,  9]], dtype=int32)>

In [95]:
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  9],
       [10,  7],
       [ 3, 10]], dtype=int32)>

In [98]:
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3, 10],
       [ 4,  9]], dtype=int32)>

⚡If we use the Operation Level random Seed, everytime that we run the cell we will get a different result. However, if we use Global Level Random Seed we can get the same result.

**Important**: It looks like if want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed. 

In [103]:
tf.random.set_seed(42) # It is called the Global Level Random Seed 
tf.random.shuffle(not_shuffled, seed = 42) # This seed is called Operation Level Random Seed (based on the TensorFlow Documentation)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  9],
       [ 3, 10]], dtype=int32)>

### Other ways to create tensors:

In [104]:
# Create a Tensor with all ones
tf.ones([5, 3])

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [107]:
# Create a tensor of all zeroes
tf.zeros(shape = (5, 3))

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into Tensors

The main difference between NumPy arrays and TensorFlow tensors is that Tensors can be run on a GPU (much faster for numerical computing). Otherwise they are very similar. 

In [108]:
# You can also turn NumPy arrays into Tensors
# Import NumPy
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32) # Create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # Conventionally, Capital letter is used for matrix or Tensor
# y = tf.constant(vector) # None_capital letter is used for Vector 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [119]:
A = tf.constant(numpy_A) # We just converted the NumPy array to form of a Tensor by passing it into tf.constant()
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [120]:
A.ndim

1

In [122]:
A = tf.constant(numpy_A, shape = (2, 3, 4))
B = tf.constant(numpy_A)

A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [125]:
2 * 3 * 4 # For example, we cannot say 2 * 3 * 5 = 30. We'll get error because the shape should be same as the original shape. 
#In other words, we have 24 elements not 30.

24

In [126]:
2 * 3 * 5

30

In [129]:
C = tf.constant(numpy_A, shape = (3, 8)) # It also works because it is equal to 24 again.
D = tf.constant(numpy_A)

C, D

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [130]:
3 * 8

24