In [ ]:
import tensorflow as tf
print(tf.__version__)

2.7.0


### Aggregating Tensors

Considering tensors from multiple values down to a smaller amount of values.

In [ ]:
# Getting the absolute values
A = tf.constant([-3, -8])
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-3, -8], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(A)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 8], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* get the maximum
* get the mean of a tensor
* get the sum of a tensor

In [10]:
# Create a random tensor with values between 0 and 10 of size 50
B = tf.random.Generator.from_seed(42)
B = B.normal((3, 2))
B

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [11]:
tf.math.reduce_min(B)

<tf.Tensor: shape=(), dtype=float32, numpy=-1.8107855>

In [12]:
tf.math.reduce_max(B)

<tf.Tensor: shape=(), dtype=float32, numpy=0.07595026>

In [13]:
tf.math.reduce_mean(B)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.6748808>

In [15]:
import numpy as np
E = tf.constant(np.random.randint(0, 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([89, 15, 11, 15, 71, 66, 14, 85, 72, 14, 97, 14, 81, 60, 70, 95, 15,
       20, 33, 80, 11, 11, 23, 61, 35, 84, 71, 55, 29, 52, 43, 80, 11, 55,
       78, 44, 87, 41, 54, 56, 97, 67, 41,  8, 54, 76, 49, 76, 31,  7])>

In [19]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [20]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [21]:
# Find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [26]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [28]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2504>

In [35]:
# To find the variance of our tensor we need access to tensorflow probability
#Using tfp --> tensorflow probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=794>

In [37]:
# Find the standard deviation (std)
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.184278>

In [38]:
tf.math.reduce_std(E)

TypeError: ignored

If you get the TypeError go to the documentation examples and check out the types that they are using in the example workflows. 

In [39]:
# Find the variance of our E tensor
tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=794.3535>

#### Find the positional maximum and minimum
* At which index of a tensor or of a row, does the maxiumum value occur. It is usefull when you trainthe model and want to find the maximum probability in a certain index.
* In other words, if we want to find the maximum element position of G meaning at which index does the maximum value occur. 


In [41]:
# Create a new tensor for finding positionalminimum and maximum
tf.random.set_seed(42)
G = tf.random.uniform(shape = [50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [43]:
# Find the positional maximum
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [45]:
# Index on our largest value position
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [46]:
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [50]:
# Check for equality 
assert G[tf.argmax(G)] == tf.reduce_max(G) # With assert we will get error if it's False

In [51]:
G[tf.argmax(G)] == tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [53]:
# Find the positional minimum
tf.argmin(G)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [55]:
# Find the minimum using the positional minimum index
G[tf.argmin(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [57]:
# Create a tensor to get started
tf.random.set_seed(42)
E = tf.constant(tf.random.uniform(shape = [50]), shape = (1, 1, 1, 1, 50))
E

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [58]:
E.shape

TensorShape([1, 1, 1, 1, 50])

In [60]:
E_squeezed = tf.squeeze(G) # It removes dimensions of size 1 from the shape of a tensor
E_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [62]:
E_squeezed.shape

TensorShape([50])