In [1]:
import tensorflow as tf
print(tf.__version__)

2.7.0


## One-Hot Encoding
 

In [4]:
# Create a list of indecies
some_list = [0, 1, 2, 3] # Could be red, green, blue, purple

#One-hot encode our list of indecies
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [8]:
# Specify custom values for one hot encoding 
tf.one_hot(some_list, depth = 4, on_value = "Yes", off_value = "No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

In [13]:
tf.one_hot(some_list, depth = 4, on_value = 2, off_value = 3)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[2, 3, 3, 3],
       [3, 2, 3, 3],
       [3, 3, 2, 3],
       [3, 3, 3, 2]], dtype=int32)>