In [ ]:
import tensorflow as tf
import numpy as np

### Tensors and NumPy
TensorFlow interacts beautifully with NumPy arrays.

In [ ]:
# Create a tensor directly from NumPy array
A = tf.constant(np.array([1, 2, 3]))
A

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [ ]:
# Convert a tensor to NumPy array
np.array(A), type(np.array(A))

(array([1, 2, 3]), numpy.ndarray)

In [ ]:
# Convert tensor A to a NumPy array
A.numpy(), type(A.numpy())

(array([1, 2, 3]), numpy.ndarray)

In [6]:
# The default type of each are slightly different 
numpy_A = tf.constant(np.array([4., 2., 5.]))
tensor_A = tf.constant([4., 2., 5.])
# Cehck the datatype of each
numpy_A.dtype, tensor_A.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [7]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [8]:
tf.config.list_physical_devices("GPU")

[]

In [3]:
# Just change the runtime on Google colb to GPU
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

**Note:** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.

In [4]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
!nvidia-smi

Thu Nov 25 00:14:07 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8    27W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------