In [1]:
import tensorflow as tf
import numpy as np

### Tensors and NumPy
TensorFlow interacts beautifully with NumPy arrays.

In [2]:
# Create a tensor directly from NumPy array
A = tf.constant(np.array([1, 2, 3]))
A

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [3]:
# Convert a tensor to NumPy array
np.array(A), type(np.array(A))

(array([1, 2, 3]), numpy.ndarray)

In [4]:
# Convert tensor A to a NumPy array
A.numpy(), type(A.numpy())

(array([1, 2, 3]), numpy.ndarray)

In [5]:
# The default type of each are slightly different 
numpy_A = tf.constant(np.array([4., 2., 5.]))
tensor_A = tf.constant([4., 2., 5.])
# Cehck the datatype of each
numpy_A.dtype, tensor_A.dtype

(tf.float64, tf.float32)